<?xml version="1.0"?>
<Coupons>	
<item>
<CouponsImage><![CDATA[coupons/coupon1.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon2.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon3.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon4.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon5.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon1.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon2.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon3.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon4.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
<item>
<CouponsImage><![CDATA[coupons/coupon5.png]]></CouponsImage>
<CouponsLink><![CDATA[xxx.html]]></CouponsLink>
</item>
</Coupons>

